sudo: false
language: python
python:
  - "2.7"

os: linux

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database helios;' -U postgres

script: "python -Wall manage.py test"

jobs:
  include:
  - dist: bionic
    addons:
      postgresql: "10"
